name: MSBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: SAPIForVOICEVOX.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: x86
            InstallerProjectPath: Setup\Setup.vdproj

          - platform: x64
            InstallerProjectPath: Setup64\Setup64.vdproj

    steps:
    - uses: actions/checkout@v3

    - name: Add devenv to PATH
      uses: seanmiddleditch/gha-setup-vsdevenv@master
      run: DisableOutOfProcBuild.exe

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    # - name: Build
    #   working-directory: ${{env.GITHUB_WORKSPACE}}
    #   run: devenv.com ${{env.SOLUTION_FILE_PATH}} /build "${{env.BUILD_CONFIGURATION}}|${{matrix.platform}}"

    - name: Create Installer
      run: devenv.com ${{env.SOLUTION_FILE_PATH}}  /project ${{matrix.InstallerProjectPath}} /build "${{env.BUILD_CONFIGURATION}}|${{matrix.platform}}"
